### ISSUE TITLE
do not work anymore 

### ISSUE THREAD

**Issue by w-famy** [airtai/faststream-gen#180]
I just installed using pip install faststream-gen under python3.12 environement.

faststream_gen --help crash see bellow:

faststream_gen --help
/home/bill/virtual/stream/lib/python3.12/site-packages/langchain/embeddings/__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.embeddings import OpenAIEmbeddings`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/bill/virtual/stream/lib/python3.12/site-packages/langchain/vectorstores/__init__.py:35: LangChainDeprecationWarning: Importing vector stores from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.vectorstores import FAISS`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/bill/virtual/stream/bin/faststream_gen", line 5, in <module>
    from faststream_gen.cli import app
  File "/home/bill/virtual/stream/lib/python3.12/site-packages/faststream_gen/cli.py", line 14, in <module>
    from faststream_gen._code_generator.app_description_validator import (
  File "/home/bill/virtual/stream/lib/python3.12/site-packages/faststream_gen/_code_generator/app_description_validator.py", line 13, in <module>
    from .chat import CustomAIChat
  File "/home/bill/virtual/stream/lib/python3.12/site-packages/faststream_gen/_code_generator/chat.py", line 48, in <module>
    openai.error.RateLimitError,
    ^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'error'

I install pip install -U langchain-community too.

**Comment by saadhypng** [comment]
Hey @w-famy 

Just run pip install openai==0.28, there is an issue with the latest version that is causing this issue.
